# coding: utf-8

"""
    Voicer API - Система озвучки текста

     ## Описание сервиса  **Voicer API** — это современная система для преобразования текста в речь с использованием технологий ElevenLabs.  ### Основные возможности: - Более 50 голосов различных языков и стилей - Быстрая обработка больших текстов (до 500,000 символов) - Отслеживание прогресса выполнения задач в реальном времени - Безопасная авторизация по токенам - Простая интеграция через REST API  ### Базовый URL: ``` https://elevenlabs-unlimited.net/api/v1 ```  ### Авторизация: Все запросы требуют заголовок авторизации: ``` Authorization: Bearer YOUR_API_TOKEN ```  ### Поддерживаемые модели: - `eleven_multilingual_v2` — Многоязычная модель (рекомендуется) - `eleven_turbo_v2` — Быстрая модель для коротких текстов   - `eleven_turbo_v2_5` — Улучшенная быстрая модель - `eleven_v3` — Новейшая модель с улучшенным качеством  ### Поддержка: - Email: support@voicer-api.com - Telegram: @voicer_support     

    The version of the OpenAPI document: 2.0.0
    Contact: support@voicer-api.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_create_voice_task_api_v1_voice_synthesize_post(self) -> None:
        """Test case for create_voice_task_api_v1_voice_synthesize_post

        Создать задачу озвучки
        """
        pass

    def test_download_audio_api_v1_voice_download_task_id_get(self) -> None:
        """Test case for download_audio_api_v1_voice_download_task_id_get

        Скачать аудиофайл
        """
        pass

    def test_get_task_status_api_v1_voice_status_task_id_get(self) -> None:
        """Test case for get_task_status_api_v1_voice_status_task_id_get

        Проверить статус задачи
        """
        pass

    def test_get_user_stats_api_v1_user_stats_get(self) -> None:
        """Test case for get_user_stats_api_v1_user_stats_get

        Статистика пользователя
        """
        pass


if __name__ == '__main__':
    unittest.main()
