# coding: utf-8

"""
    Voicer API - Система озвучки текста

     ## Описание сервиса  **Voicer API** — это современная система для преобразования текста в речь с использованием технологий ElevenLabs.  ### Основные возможности: - Более 50 голосов различных языков и стилей - Быстрая обработка больших текстов (до 500,000 символов) - Отслеживание прогресса выполнения задач в реальном времени - Безопасная авторизация по токенам - Простая интеграция через REST API  ### Базовый URL: ``` https://elevenlabs-unlimited.net/api/v1 ```  ### Авторизация: Все запросы требуют заголовок авторизации: ``` Authorization: Bearer YOUR_API_TOKEN ```  ### Поддерживаемые модели: - `eleven_multilingual_v2` — Многоязычная модель (рекомендуется) - `eleven_turbo_v2` — Быстрая модель для коротких текстов   - `eleven_turbo_v2_5` — Улучшенная быстрая модель - `eleven_v3` — Новейшая модель с улучшенным качеством  ### Поддержка: - Email: support@voicer-api.com - Telegram: @voicer_support     

    The version of the OpenAPI document: 2.0.0
    Contact: support@voicer-api.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.task_response import TaskResponse

class TestTaskResponse(unittest.TestCase):
    """TaskResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaskResponse:
        """Test TaskResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaskResponse`
        """
        model = TaskResponse()
        if include_optional:
            return TaskResponse(
                task_id = '550e8400-e29b-41d4-a716-446655440000',
                status = 'pending',
                message = 'Задача успешно создана и добавлена в очередь',
                chunks_count = 3,
                estimated_time = 45.5
            )
        else:
            return TaskResponse(
                task_id = '550e8400-e29b-41d4-a716-446655440000',
                status = 'pending',
                message = 'Задача успешно создана и добавлена в очередь',
                chunks_count = 3,
                estimated_time = 45.5,
        )
        """

    def testTaskResponse(self):
        """Test TaskResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
