# coding: utf-8

# flake8: noqa
"""
    Voicer API - Система озвучки текста

     ## Описание сервиса  **Voicer API** — это современная система для преобразования текста в речь с использованием технологий ElevenLabs.  ### Основные возможности: - Более 50 голосов различных языков и стилей - Быстрая обработка больших текстов (до 500,000 символов) - Отслеживание прогресса выполнения задач в реальном времени - Безопасная авторизация по токенам - Простая интеграция через REST API  ### Базовый URL: ``` https://elevenlabs-unlimited.net/api/v1 ```  ### Авторизация: Все запросы требуют заголовок авторизации: ``` Authorization: Bearer YOUR_API_TOKEN ```  ### Поддерживаемые модели: - `eleven_multilingual_v2` — Многоязычная модель (рекомендуется) - `eleven_turbo_v2` — Быстрая модель для коротких текстов   - `eleven_turbo_v2_5` — Улучшенная быстрая модель - `eleven_v3` — Новейшая модель с улучшенным качеством  ### Поддержка: - Email: support@voicer-api.com - Telegram: @voicer_support     

    The version of the OpenAPI document: 2.0.0
    Contact: support@voicer-api.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


if __import__("typing").TYPE_CHECKING:
    # import models into model package
    from elevenlabsunlimited.models.http_validation_error import HTTPValidationError
    from elevenlabsunlimited.models.location_inner import LocationInner
    from elevenlabsunlimited.models.task_response import TaskResponse
    from elevenlabsunlimited.models.user_stats import UserStats
    from elevenlabsunlimited.models.validation_error import ValidationError
    from elevenlabsunlimited.models.voice_request import VoiceRequest
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from elevenlabsunlimited.models.http_validation_error import HTTPValidationError
from elevenlabsunlimited.models.location_inner import LocationInner
from elevenlabsunlimited.models.task_response import TaskResponse
from elevenlabsunlimited.models.user_stats import UserStats
from elevenlabsunlimited.models.validation_error import ValidationError
from elevenlabsunlimited.models.voice_request import VoiceRequest

""",
            name=__name__,
            doc=__doc__,
        )
    )
