# coding: utf-8

"""
    Voicer API - Система озвучки текста

     ## Описание сервиса  **Voicer API** — это современная система для преобразования текста в речь с использованием технологий ElevenLabs.  ### Основные возможности: - Более 50 голосов различных языков и стилей - Быстрая обработка больших текстов (до 500,000 символов) - Отслеживание прогресса выполнения задач в реальном времени - Безопасная авторизация по токенам - Простая интеграция через REST API  ### Базовый URL: ``` https://elevenlabs-unlimited.net/api/v1 ```  ### Авторизация: Все запросы требуют заголовок авторизации: ``` Authorization: Bearer YOUR_API_TOKEN ```  ### Поддерживаемые модели: - `eleven_multilingual_v2` — Многоязычная модель (рекомендуется) - `eleven_turbo_v2` — Быстрая модель для коротких текстов   - `eleven_turbo_v2_5` — Улучшенная быстрая модель - `eleven_v3` — Новейшая модель с улучшенным качеством  ### Поддержка: - Email: support@voicer-api.com - Telegram: @voicer_support     

    The version of the OpenAPI document: 2.0.0
    Contact: support@voicer-api.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self

class TaskResponse(BaseModel):
    """
    ## Ответ при создании задачи озвучки  Содержит информацию о созданной задаче и прогнозируемом времени выполнения.
    """ # noqa: E501
    task_id: StrictStr = Field(description="Уникальный идентификатор задачи")
    status: StrictStr = Field(description="Текущий статус задачи")
    message: StrictStr = Field(description="Сообщение о результате создания")
    chunks_count: StrictInt = Field(description="Количество фрагментов для обработки")
    estimated_time: Union[StrictFloat, StrictInt] = Field(description="Примерное время выполнения в секундах")
    __properties: ClassVar[List[str]] = ["task_id", "status", "message", "chunks_count", "estimated_time"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TaskResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TaskResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "task_id": obj.get("task_id"),
            "status": obj.get("status"),
            "message": obj.get("message"),
            "chunks_count": obj.get("chunks_count"),
            "estimated_time": obj.get("estimated_time")
        })
        return _obj


