# coding: utf-8

# flake8: noqa

"""
    Voicer API - Система озвучки текста

     ## Описание сервиса  **Voicer API** — это современная система для преобразования текста в речь с использованием технологий ElevenLabs.  ### Основные возможности: - Более 50 голосов различных языков и стилей - Быстрая обработка больших текстов (до 500,000 символов) - Отслеживание прогресса выполнения задач в реальном времени - Безопасная авторизация по токенам - Простая интеграция через REST API  ### Базовый URL: ``` https://elevenlabs-unlimited.net/api/v1 ```  ### Авторизация: Все запросы требуют заголовок авторизации: ``` Authorization: Bearer YOUR_API_TOKEN ```  ### Поддерживаемые модели: - `eleven_multilingual_v2` — Многоязычная модель (рекомендуется) - `eleven_turbo_v2` — Быстрая модель для коротких текстов   - `eleven_turbo_v2_5` — Улучшенная быстрая модель - `eleven_v3` — Новейшая модель с улучшенным качеством  ### Поддержка: - Email: support@voicer-api.com - Telegram: @voicer_support     

    The version of the OpenAPI document: 2.0.0
    Contact: support@voicer-api.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "VoiceApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "HTTPValidationError",
    "LocationInner",
    "TaskResponse",
    "UserStats",
    "ValidationError",
    "VoiceRequest",
]

if __import__("typing").TYPE_CHECKING:
    # import apis into sdk package
    from openapi_client.api.voice_api import VoiceApi as VoiceApi
    
    # import ApiClient
    from openapi_client.api_response import ApiResponse as ApiResponse
    from openapi_client.api_client import ApiClient as ApiClient
    from openapi_client.configuration import Configuration as Configuration
    from openapi_client.exceptions import OpenApiException as OpenApiException
    from openapi_client.exceptions import ApiTypeError as ApiTypeError
    from openapi_client.exceptions import ApiValueError as ApiValueError
    from openapi_client.exceptions import ApiKeyError as ApiKeyError
    from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
    from openapi_client.exceptions import ApiException as ApiException
    
    # import models into sdk package
    from openapi_client.models.http_validation_error import HTTPValidationError as HTTPValidationError
    from openapi_client.models.location_inner import LocationInner as LocationInner
    from openapi_client.models.task_response import TaskResponse as TaskResponse
    from openapi_client.models.user_stats import UserStats as UserStats
    from openapi_client.models.validation_error import ValidationError as ValidationError
    from openapi_client.models.voice_request import VoiceRequest as VoiceRequest
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            ("__version__", __version__),
            ("__all__", __all__),
            """# import apis into sdk package
from openapi_client.api.voice_api import VoiceApi as VoiceApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.http_validation_error import HTTPValidationError as HTTPValidationError
from openapi_client.models.location_inner import LocationInner as LocationInner
from openapi_client.models.task_response import TaskResponse as TaskResponse
from openapi_client.models.user_stats import UserStats as UserStats
from openapi_client.models.validation_error import ValidationError as ValidationError
from openapi_client.models.voice_request import VoiceRequest as VoiceRequest

""",
            name=__name__,
            doc=__doc__,
        )
    )
